title: Zajímavá místa Brna
baseURL: https://dovikba07.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Úvodní stránka
      url: /
      weight: 10
    - name: Archiv
      identifier: post
      url: /post/
      weight: 20

params:
  description: některá i méně známá
  authors: Autoři

